// Récupération par id
// console.log(document.getElementById("image"));
// console.log(document.querySelector("#image"));


// Récupération par classe
// console.log(document.querySelector(".Hello"));

// Récuparation par tag 
// console.log(document.querySelector("p"));
// console.log(document.querySelector("img[alt='plage']"));

// Récupération plusieurs références
// console.log(document.querySelectorAll(".test"));